# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97938f97f9f5a68c2ec0d8d71b8bd4661bcbd9490935ef1f9b43abede8f095ace35a6e4d3aae387fdb0e32ecc964080f11711bb1dd820ff280821645e54dc6d1

test:
  secret_key_base: 35ea8e0721ace5826178ec9fa2bbb44ef0a31a66006a242d8a8329c7f1e335863ae4da03947bc3b54d3b50e5e76a9598a4846b28e6fc3e771dc58084dd7c187b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
